### PR TITLE
Update for new PICs

### PR DESCRIPTION
**Pull request by crosland**

### CODE REVIEW

**Comment by spikyian** [comment]
There are erroneous commas on the end of lines in the CSV file. These then get carried through to the language specific generated files. These need to be fixed before merge.

**Comment by crosland** [comment]
They are there in the original! See https://github.com/MERG-DEV/cbusdefs/blob/master/cbusdefs.csv

**Comment by spikyian** [comment]
The master does not have the extra commas. If you check the file diff in the PR you can see the extra comms in the new files:
image

**Comment by crosland** [comment]
AH, OK, I was only looking at the lines around my changes.

The problem is, it's a .csv file so if viewed in, say excel, which is probably the default on may systems, the commas are added due to the number of cells on line 64.

I will have another go.

**Pull request closed without merging**
