### PR TITLE
Updated cbusdefs.csv to correct OpCode BOOT to BOOTM

### PR DESCRIPTION
**Pull request by RichardCrawshaw**
Regenerated C# classes.

### CODE REVIEW

**Comment by spikyian** [comment]
Why have only the C# files been generated?

**Comment by RichardCrawshaw** [comment]
> Why have only the C# files been generated?

They were the ones I needed, so I generated them for myself; I included them in the PR because other contributors may not have the means to generate them.
I didn't have immediate access to the tools to generate the other ones.

**Comment by spikyian** [comment]
It looks as if you have manually generated CbusDefs/* instead of using the generate scripts. That defeats the whole purpose of the csv file.

We now have two versions of cbusdefs.cs and cbusdefsenums within the same repository - quite confusing. If you need the CbusDefs/* version then we need to auto generate them from the CSV. Do we also need the lowercase versions in the top directory?

**Comment by pnbgit** [comment]
Firstly, my apologies that I havn't been active on this repository for a while.

As Ian has said, the generate scripts should be used after editing the csv fie so that all language files are generated.

Richard - are you working in your own branch for any changes so we can carefully manage merging anything back into Master?

I do have a particular concern about this change,  It is very important that we do not make changes that will break existing code.  Changing the name of an opcode is very likely to break existing code.  I checked this one, it would break at least the following modules firmware build:
CANACC4/CANSOL
CANACC5-8/CANMIO-OUT/CANBIP-OUT/CANOUT/CANINOUT
CANACE8c/CANINP/CANACE8MIO
CANACE3c
CANCMD
CANEther
as well as others
I think it also breaks the build of the PIC CBUSLIB which is used by at least CANMIO and CANCOMPUTE (Ian - would you concur with that?)
Whilst the fix to the source for any one module might be trivial, I think it is a bad idea to make a change that breaks the build for so many modules. I think that it has been OPC_BOOT in cbusdefs for ever, so we have to live with that, perhaps we should just add a comment that this corresponds to OPC_BOOTM in the CBUS spec?
I'm also not quite clear which version we are working on.

I'm also a bit unclear what version we are working on. THere is a realease on Github for version 8t, so if that has been released, we should not longer be making changes to it and we should be working on version 8u?

**Comment by spikyian** [comment]
Modules would only need to pick up the change for BOOOTM when making a change that needed an updated cbusdefs. Then they would need to update their code to reference the corrected spelling which isn't a big deal so I was happy enough for the corection, which I had noticed but hadn't bothered to correct. It isn't a big problem either way.

I thought we had agreed to drop the letter versioning in github. If people still wanted to have a letter version in a wiki copy then that is fine but deciding when to update that file and change its version is an outdated problem  which I am no longer concerned about.

The README.md should have the instructions for updating cbusdefs.

**Comment by pnbgit** [comment]
We agreed  to  drop having the version number in the include filenames, but each release still needs a version number otherwise it becomes a mess. It is just that the inculde file, and then fail becuase of changes of his sort.  Note that cbusdefs8uetc can still be uploaded to the wiki after each release if developers want one with the version number in it.

I don't think we should be making non-backwards compatible changes like renaming opcodes, when keeping it as it was causes no problems, IMHO.

It is still the plan,  to move to versioning of the form 9.x.y where x is the sub-version of the spec (eg: 9.0), and y is any update to cbusdefs still referencing the same CBUS spec, eg: 9.0.1 I need to find time to get that process moving with Mike and Gil.

Once that is sorted out, we will need to document that versioning. For the moment, I guess we continue with 8x where x is a letter.

**Comment by RichardCrawshaw** [comment]
> It looks as if you have manually generated CbusDefs/* instead of using the generate scripts. That defeats the whole purpose of the csv file.
> 
> We now have two versions of cbusdefs.cs and cbusdefsenums within the same repository - quite confusing. If you need the CbusDefs/* version then we need to auto generate them from the CSV. Do we also need the lowercase versions in the top directory?

I ran the .NET T4 code generation templates. They generates new versions of cbusdefs.cs and cbusdefsenums.cs which overwrite the previous versions. So unless there is something weird going on with the repository I don't understand why you say there are two versions of them. The .NET T4 code generation templates uses the csv file. Updating that to be in line with the published spec was the whole purpose of the change I made.

**Comment by RichardCrawshaw** [comment]
> As Ian has said, the generate scripts should be used after editing the csv fie so that all language files are generated.

Running the generate scripts only makes sense if one has the capability to run them reliably. As was found out when I made a previous change there are differences between the behaviour of the scripting engine on Windows and Mac / Linux. I don't have immediate access to a non-Windows version, so I decided not to run the generate scripts, but instead to explicitly state that the C# files had been updated, which were what I needed and what I used to confirm that my change was effective. Maybe I should have been even more explicit about what had and hadn't been run and why.

> Richard - are you working in your own branch for any changes so we can carefully manage merging anything back into Master?

I forked the repository some time back into my own. I then updated my fork from master in cbusdefs. Pulled my forked master locally, made and tested the change. Committed my changed locally, pushed to my forked master, then submitted a PR to cbusdefs.

> I do have a particular concern about this change, It is very important that we do not make changes that will break existing code. Changing the name of an opcode is very likely to break existing code. I checked this one, it would break at least the following modules firmware build: CANACC4/CANSOL CANACC5-8/CANMIO-OUT/CANBIP-OUT/CANOUT/CANINOUT CANACE8c/CANINP/CANACE8MIO CANACE3c CANCMD CANEther as well as others I think it also breaks the build of the PIC CBUSLIB which is used by at least CANMIO and CANCOMPUTE (Ian - would you concur with that?) Whilst the fix to the source for any one module might be trivial, I think it is a bad idea to make a change that breaks the build for so many modules. I think that it has been OPC_BOOT in cbusdefs for ever, so we have to live with that, perhaps we should just add a comment that this corresponds to OPC_BOOTM in the CBUS spec?

Pete, I'm going to have to strongly disagree with you here. By failing to update to correct an error in a fundamental document simply persists the fault. It causes other people who are not across the history to apply bodge fixes to their code to deal with the problem. The whole purpose of a document such as cbusdefs is to be as correct as possible.

I have code that uses cbusdefs as its gold standard. It also needs much fuller descriptions of the op-codes. So I have generated similar data (cbusopcodes.txt) file that contain that extra detail all taken from 6b (and soon to include changes from 6c). Both 6b and 6c say BOOTM, so that is what I have gone with. However, the mismatch between cbusdefs and cbusopcodes causes tests to fail because the tests are generated based on cbusdefs and so expects a BOOT opcode, while the code generated from cbusopcodes produces BOOTM.
Now it would be possible for me to change cbusopcodes.txt to specify BOOT to match cbusdefs, but that will cause confusion because other contributors and users of the code will be expecting BOOTM. In my view it is much better to fix the problem once and for all, rather than persisting an error.

> I'm also a bit unclear what version we are working on. There is a realease on Github for version 8t (Sep 2020), so if that has been released, we should not longer be making changes to it and we should be working on version 8u?
> 
> Apoogies to Richard if the docs are not making it clear what should be done when editing cbusdefs, perhaps we need an updated doc for CBUS developers coming new to this?

I'm not really across your release process. Do you label the releases in github when they are made?

**Comment by RichardCrawshaw** [comment]
Pete

> It is still the plan, to move to versioning of the form 9.x.y where x is the sub-version of the spec (eg: 9.0), and y is any update to cbusdefs still referencing the same CBUS spec, eg: 9.0.1 I need to find time to get that process moving with Mike and Gil.

Not particularly my problem, but I would caution against doing this. There could well be changes to the spec that don't involve any opcode or similar changes. You would then be in the situation of needing to release a change simply because the spec version changed. Similarly, but in reverse, and more likely, there might be a need to change cbusdefs when there was no change in the spec. It then becomes difficult to relate the two: not everyone will want to be using the latest CBUS spec.

I would suggest that there is a simply a data point in cbusdefs that links the version of this repository with the version of the CBUS spec.

Just my twopennethworth, having seen this type of hard linking cause headaches in the past, I felt it to be the right thing to pass it on.

**Comment by spikyian** [comment]
It would seem we have a few issues:
**A**) In this PR we need to decide whether BOOT will be renamed to BOOTM. I don't have strong opinions about this either way. I did consider whether both entries could be created which would work for some languages but wouldn't work where enums are used so I ruled out that idea.

**B**) It seems in a change made 2 months ago multiple copies of the .cs files were added. I see that we have

- cbusdefs.cs
- cbusdefsenums.cs
- CbusDefs/CbusDefs.cs
- CbusDefs/CbusDefs.tt
- CbusDefs/CbusDefsEnums.cs
- CbusDefs/CbusDefsEnums.tt

The two files in the top level directory seem to be created correctly by generate_cs.sh and generate_cs_enums.sh.
I don't see where the files in the subdirectly are created.

**C**) I don't like having the separate scripts generate_cs.sh and generate_cs_enums.sh as this allows these to be ran separately from the rest of generate.sh. We should combine the scripts into generate.sh.

The instructions need to be made clearer that all the generated files must be updated when a change to the CSV file is made otherwise the files will not be consistent. generate.sh should be used for this.

I use git bash on Windows to run generate.sh, I do recall someone reporting a problem when running in another way but generate.sh should be compatible with multiple platforms.

**Comment by spikyian** [comment]
Oh and
**D**) We need to decide upon versioning strategy.

I suggest we take the discussion to the forum to allow a wider set of people to participate.

**Comment by pnbgit** [comment]
I suggest we hold off on versioning strategy discussion until the new versioning of the CBUS spec is in place.  The decision on versioning strategy for cbusdefs was already taken - I will write up that decision properly as it is clear not everyone fully understands how it works.

**Comment by RichardCrawshaw** [comment]
> It would seem we have a few issues: **A**) In this PR we need to decide whether BOOT will be renamed to BOOTM. I don't have strong opinions about this either way. I did consider whether both entries could be created which would work for some languages but wouldn't work where enums are used so I ruled out that idea.

I've have argued for this up thread so I won't say anything further at the moment.

> **B**) It seems in a change made 2 months ago multiple copies of the .cs files were added. I see that we have
> 
> * cbusdefs.cs
> * cbusdefsenums.cs
> * CbusDefs/CbusDefs.cs
> * CbusDefs/CbusDefs.tt
> * CbusDefs/CbusDefsEnums.cs
> * CbusDefs/CbusDefsEnums.tt
> 
> The two files in the top level directory seem to be created correctly by generate_cs.sh and generate_cs_enums.sh. I don't see where the files in the subdirectly are created.

The two .tt files are the Visual Studio T4 templates that generate the adjacent .cs files. This is the considered correct way to generate files for .NET and Visual Studio. Standard practice is to have one T4 template for each file that is wanted. They all use one "model": in this case cbusdefs.csv.

I seem to recall that there was discussion of removing the two .cs files from the root directory. I can't remember what the outcome of that discussion was; either leave them, or remove them but the removal didn't happen. At the moment I think that the C# files should be generated by the T4 template run via Visual Studio, and that the generate_cs files should be removed. (I may have had a different opinion previously, I can't remember; if I did I've changed my mind.)

> **C**) I don't like having the separate scripts generate_cs.sh and generate_cs_enums.sh as this allows these to be ran separately from the rest of generate.sh. We should combine the scripts into generate.sh.
> 
> The instructions need to be made clearer that all the generated files must be updated when a change to the CSV file is made otherwise the files will not be consistent. generate.sh should be used for this.

I also recall discussion about not generating output files, or at least not including any generated output in the repository. Effectively making the generation of the files the responsibility of the person who wants to use them.

> I use git bash on Windows to run generate.sh, I do recall someone reporting a problem when running in another way but generate.sh should be compatible with multiple platforms.

I found that git bash on Windows behaved differently to how it behaved on Max / Linux. I can't now remember the details; I believe that the discussion occurred on the forum so it could be found. And it was this that prompted the discussion about whether to include the generated output in the repository. This was part of the reason for me not generating non C# files.

If changes are made for one language how does someone who is not familiar with another language test that their changes haven't generated something that is garbage? Particularly someone who doesn't have the tools to compile (or interpret) that language. I think I'm the only .NET developer who is contributing to this repository in any way (happy to be corrected). I am by no stretch of the imagination either an assembler programmer or a C/C++ programmer. So if one of you (who are not .NET developers) make a change to the generated C# code how do you ensure that you have generated valid code? And v.v. me with assembler or C/C++? To my mind the solution is that one doesn't; the repository just contains the generation script / templates / whatever, and the source data.

**Comment by spikyian** [comment]
I suppose that is the fundamental question of whether the repo should contain the language specific, generated files.
At the moment my preference is that it should as it saves the majority of developers from having to work out how and getting the tools to generate them. By having the generate.sh script this should ensure that the generated files are correct. Obviously any changes to sections of generate.sh need to be done by someone familiar with that section's language. Running the generate.sh script shouldn't require any language specific knowledge.
Maybe for C# a different approach of just having the .tt files and not the .cs files is sufficent?

**Comment by RichardCrawshaw** [comment]
> I suppose that is the fundamental question of whether the repo should contain the language specific, generated files.

That is your (collective) call.

> Maybe for C# a different approach of just having the .tt files and not the .cs files is sufficent?

I would be happy with that. Pretty much any .NET developer is going to have the tools to generate the .cs files from the .tt files. (I'm not sure about Mono, though! But VS is a free download, so should be easy enough.) Just need the instructions. I'm happy to write some words if you want; let me know.

**Comment by pnbgit** [comment]
I've added a comment in the forum discussion, which sets out the planned versioning strategy in more detail. As stated there, I think a full release of a new version of cbusdefs should always include all the language files. What is in the repository between releases will always be WIP, and a developer can do what they like in their own branch. With regards to what we do for c#, I think we need to bring the current FCU developer in on that discussion. I will drop Dave Radcliffe an email and see if he is still involved with FCU development.

**Comment by JamesThorpe** [comment]
One potential solution to the generated files living in the repository would be to use GitHub actions to generate them upon merge.  It was me that had a problem running generate.sh locally at one point - think it was something to do with automatic handling (or not) of line endings that was causing problems.  By moving the running of that server side to somewhere known, it would make it consistent on every version.  Given GitHub is now MS owned etc, I would be very surprised if there wasn't also a way to run the T4 generation too.

On the c# files - I believe Richard originally added the cbusdefs.cs file.  I added the cbusdefsenums.cs version.  Richard has subsequently moved these to the T4 method of generation within the subfolder - I'm fully on board with this approach, and would be happy to see the top level files (and any generate scripts associated with them) disappear.

**Comment by RichardCrawshaw** [comment]
I'm closing this PR as there is clearly no genuine interest in accepting it.

**Pull request closed without merging**
